apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: example-shinyproxy
spec:
  proxy:
    title: Open Analytics Shiny Proxy
    logoUrl: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landingPage: /
    heartbeatRate: 10000
    heartbeatTimeout: 60000
    port: 8080
#    authentication: simple
    containerBackend: kubernetes
    authentication: ldap
    ldap:
      url: ldap://ldap.forumsys.com:389/dc=example,dc=com
      user-dn-pattern: uid={0}
      group-search-filter: (uniqueMember={0})
      manager-dn: cn=read-only-admin,dc=example,dc=com
      manager-password: ${LDAP_PASSWORD}
    users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    specs:
    - id: 01_hello
      displayName: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      containerCmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      containerImage: openanalytics/shinyproxy-demo
      kubernetes-pod-patches: |
       - op: replace
         path: /metadata/namespace
         value: my-namespace
    - id: 06_tabsets
      container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
      container-image: openanalytics/shinyproxy-demo

  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env
      value:
        - name: LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
             name: ldap-password
             key: password
