---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: shinyproxy
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        ports:
         - containerPort: 6379
        args: [ "--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-password
                key: password

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: shinyproxy
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: shinyproxy
type: Opaque
data:
  password: bXlQYXNzd29yRA==
