apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - namespaces.yaml
 - dependencies
 - secrets.yaml
 - operator.serviceAccount.yaml
 - shinyproxy.serviceAccount.yaml
 - deployment.yaml
