---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  namespace: shinyproxy
data:
  password: cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  namespace: my-namespace
data:
  password: cGFzc3dvcmQ=
type: Opaque
