---
# ServiceAccount to run the operator in
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: shinyproxy
  name: shinyproxy-operator-sa
---
# Role for the SerivceAcount of the operator
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shinyproxy
  name: shinyproxy-operator-role
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openanalytics.eu"]
  resources: ["shinyproxies", "shinyproxies/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["customresource"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
#- apiGroups: ["apiextensions.k8s.io"]
  #resources: ["customresourcedefinitions"]
  #verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Make it possible for the operator to access the ShinyProxy namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-rolebinding
  namespace: shinyproxy
subjects:
- kind: ServiceAccount
  namespace: shinyproxy
  name: shinyproxy-operator-sa
roleRef:
  kind: Role
  name: shinyproxy-operator-role
  apiGroup: rbac.authorization.k8s.io
---
# Role for the Operator to access Pods (i.e. apps) in my-namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: shinyproxy-operator-pods-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Bind the shinyproxy-operator-pods-role to the ServiceAccount
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-pods-rolebinding
  namespace: my-namespace
subjects:
- kind: ServiceAccount
  namespace: shinyproxy
  name: shinyproxy-operator-sa
roleRef:
  kind: Role
  name: shinyproxy-operator-pods-role
  apiGroup: rbac.authorization.k8s.io

