kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shinyproxy
  name: shinyproxy-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["openanalytics.eu"]
  resources: ["shinyproxies", "shinyproxies/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["customresource"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-role
subjects:
- kind: ServiceAccount
  namespace: shinyproxy
  name: shinyproxy-operator-sa
roleRef:
  kind: ClusterRole
  name: shinyproxy-operator-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namesapce
  name: shinyproxy-operator-role-my-ns
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-operator-role-my-ns
subjects:
- kind: ServiceAccount
  namespace: my-namespace
  name: shinyproxy-operator-sa
roleRef:
  kind: ClusterRole
  name: shinyproxy-operator-role-my-ns
  apiGroup: rbac.authorization.k8s.io

