apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: shinyproxy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-role
  namespace: shinyproxy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-rolebinding
  namespace: shinyproxy
subjects:
- kind: ServiceAccount
  name: default
  namespace: shinyproxy
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io

