apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: example-shinyproxy
  namespace: shinyproxy
spec:
  spring:
    session:
      store-type: redis
    redis:
      host: redis
      password: ${REDIS_PASSWORD}
  management:
    endpoints:
      web:
        exposure:
          include: info,health,beans,prometheus,metrics
    metrics:
      export:
        prometheus:
          enabled: true
  proxy:
    usage-stats-url: micrometer
    stop_apps_on_shutdown: false
    ha-mode: redis
    title: Open Analytics Shiny Proxy 2
    logoUrl: https://www.openanalytics.eu/shinyproxy/logo.png
    landingPage: /
    port: 8080
    containerBackend: kubernetes
    kubernetes:
      namespace: shinyproxy
      internal-networking: true
    authentication: simple
    users:
    - name: bart
      password: epviczcc
      groups: pulmonologists, specialist
    - name: thomas
      password: epviczcc
      groups: cardiologists
    - name: john
      password: epviczcc
      groups: cardiologists, specialist
    - name: demo1
      password: demo1
    - name: demo2
      password: demo2
    - name: demo3
      password: demo3
    - name: demo4
      password: demo4
    - name: demo5
      password: demo5
    specs:
    - id: 01_hello
      displayName: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      containerCmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      containerImage: openanalytics/shinyproxy-demo
      kubernetes-pod-patches: |
       - op: add
         path: /spec/containers/0/env
         value:
           - name: SOME_PASSWORD
             valueFrom:
               secretKeyRef:
                name: some-password
                key: password
       - op: replace
         path: /metadata/namespace
         value: my-namespace
    - id: 06_tabsets
      container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
      container-image: openanalytics/shinyproxy-demo
      description: Some Tabset Description 42
    - id: rstudio
      displayName: Application for everyone
      containerImage: openanalytics/shinyproxy-rstudio-ide-demo
      container-env:
        DISABLE_AUTH: true
      port: 8787
    - id: vsode
      container-image: openanalytics/shinyproxy-desktop-app-demo:vscode
      container-env:
        RELATIVE_URL_ROOT: app_direct/phaedra
      port: 80
    - id: zeppelin
      display-name: Apache Zeppelin
      container-image: apache/zeppelin:0.8.1
      port: 8080
    - id: shinyproxy-nodejs-ws
      containerImage: ledfan/shinyproxy-nodejs-ws
      port: 3000
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: LDAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: TEST_VAR
        value: TEST_VALUE
  image: openanalytics/shinyproxy:2.5.0
  imagePullPolicy: Always
  fqdn: shinyproxy-demo.local
  replicas: 1
  appNamespaces:
   - my-namespace
