# Setup a second ShinyProxy Instance in another namespace (yanamespace)
---
# namespace to run the 01_hello app in
apiVersion: v1
kind: Namespace
metadata:
  name: yanamespace
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-password
  namespace: yanamespace
data:
  password: cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: yanamespace
type: Opaque
data:
  password: bXlQYXNzd29yRA==
---
apiVersion: v1
kind: Secret
metadata:
  name: some-password
  namespace: yanamespace
data:
  password: cGFzc3dvcmQ=
type: Opaque
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-role
  namespace: yanamespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-rolebinding
  namespace: yanamespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: yanamespace
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io
apiVersion: openanalytics.eu/v1alpha1
---
kind: ShinyProxy
metadata:
  name: example-shinyproxy
  namespace: yanamespace
spec:
  spring:
    session:
      store-type: redis
    redis:
      host: redis.shinyproxy-apps
      password: ${REDIS_PASSWORD}
  proxy:
    title: Yet Another Open Analytics Shiny Proxy
    logoUrl: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landingPage: /
    heartbeatRate: 10000
    heartbeatTimeout: 60000
    port: 8080
    containerBackend: kubernetes
    kubernetes:
      namespace: yanamespace
      internal-networking: true
    authentication: simple
    users:
    - name: demo
      password: demo
    - name: demo2
      password: demo2
    specs:
    - id: 01_hello
      displayName: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      containerCmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      containerImage: openanalytics/shinyproxy-demo
      kubernetes-pod-patches: |
       - op: add
         path: /spec/containers/0/env
         value:
           - name: SOME_PASSWORD
             valueFrom:
               secretKeyRef:
                name: some-password
                key: password
    - id: 06_tabsets
      container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
      container-image: openanalytics/shinyproxy-demo
      description: Some Tabset Description 42
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: LDAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: TEST_VAR
        value: TEST_VALUE
  image: openanalytics/shinyproxy-snapshot:2.3.2-SNAPSHOT-20200922.151458
  fqdn: skipper2-demo.local

