apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: shinyproxy-apps
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-role
  namespace: shinyproxy-apps
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-rolebinding
  namespace: shinyproxy-apps
subjects:
- kind: ServiceAccount
  name: default
  namespace: shinyproxy-apps
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-role
  namespace: my-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shinyproxy-apps-rolebinding
  namespace: my-namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: shinyproxy-apps
roleRef:
  kind: Role
  name: shinyproxy-apps-role
  apiGroup: rbac.authorization.k8s.io
