apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: shinyproxy-realm1
  namespace: shinyproxy
spec:
  server:
    servlet:
      context-path: /realm1
  spring:
    session:
      store-type: redis
    redis:
      host: redis
      password: ${REDIS_PASSWORD}
  proxy:
    title: Open Analytics Shiny Proxy - Realm1
    logoUrl: https://www.openanalytics.eu/shinyproxy/logo.png
    landingPage: /
    heartbeatRate: 10000
    heartbeatTimeout: 60000
    port: 8080
    containerBackend: kubernetes
    kubernetes:
      namespace: shinyproxy
      internal-networking: true
    authentication: simple
    users:
      - name: bart
        password: epviczcc
        groups: pulmonologists, specialist
      - name: thomas
        password: epviczcc
        groups: cardiologists
      - name: john
        password: epviczcc
        groups: cardiol
    specs:
    - id: rstudio
      container-image: openanalytics/shinyproxy-rstudio-ide-demo
      container-env:
        DISABLE_AUTH: true
      port: 8787
    - id: 01_hello
      display-name: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
      container-image: openanalytics/shinyproxy-demo
    - id: 06_tabsets
      container-cmd: [ "R", "-e", "shinyproxy::run_06_tabsets()" ]
      container-image: openanalytics/shinyproxy-demo
    - id: phaedra
      container-image: openanalytics/shinyproxy-desktop-app-demo:phaedra
      container-env:
        RELATIVE_URL_ROOT: app_direct/phaedra
      port: 80
    - id: vscode
      container-image: openanalytics/shinyproxy-desktop-app-demo:vscode
      container-env:
        RELATIVE_URL_ROOT: app_direct/phaedra
      port: 80
    - id: dash-demo
      display-name: Dash Demo Application
      port: 8050
      container-cmd: [ "python", "app.py" ]
      container-image: openanalytics/shinyproxy-dash-demo
    - id: zeppelin
      display-name: Apache Zeppelin
      container-image: apache/zeppelin:0.8.1
      port: 8080
    - id: data_tables
      displayName: Data Tables
      description: Application which demonstrates Datat Tables
      containerCmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
      containerImage: ledfan/shinyproxy-datatables
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: LDAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: TEST_VAR
        value: TEST_VALUE
  image: openanalytics/shinyproxy-snapshot:2.3.2-SNAPSHOT-20201002.120450
  fqdn: shinyproxy-demo.local

