apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shinyproxy

resources:
  - ../../../bases/shinyproxy
  - resources/redis.secret.yaml
  - resources/shinyproxy.shinyproxy.yaml
  - resources/shinyproxy.namespace.yaml
