name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ]
        kubernetes: [ 'v1.21.6', 'v1.20.12', 'v1.19.16', 'v1.18.20', 'v1.17.17', 'v1.16.15']

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.16.0'
          kubernetes version:  ${{ matrix.kubernetes }}
      - name: Build with Maven
        run: mvn -B -U clean install -DskipTests
      - name: Run Tests
        run: mvn -B test

#  dependency:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run Dependency Check
#        run: mvn -Powasp-dependency-check verify -DskipTests
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v2
#        with:
#          name: dependency-check-report
#          path: target/dependency-check-report.html
#
