apiVersion: openanalytics.eu/v1alpha1
kind: ShinyProxy
metadata:
  name: shinyproxy-realm2
  namespace: shinyproxy
spec:
  spring:
    session:
      store-type: redis
    redis:
      host: redis
      password: ${REDIS_PASSWORD}
  proxy:
    title: Open Analytics Shiny Proxy - Realm2
    logoUrl: https://www.openanalytics.eu/shinyproxy/logo.png
    landingPage: /
    heartbeatRate: 10000
    heartbeatTimeout: 60000
    port: 8080
    containerBackend: kubernetes
    kubernetes:
      namespace: shinyproxy
      internal-networking: true
    authentication: simple
    users:
    - name: jack
      password: password
      groups: scientists, admin
    - name: jeff
      password: password
      groups: mathematicians
    specs:
    - id: 01_hello
      displayName: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      containerCmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      containerImage: openanalytics/shinyproxy-demo
    - id: 06_tabsets
      container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
      container-image: openanalytics/shinyproxy-demo
      description: Some Tabset Description 42
  kubernetesPodTemplateSpecPatches: |
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: LDAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-password
            key: password
    - op: add
      path: /spec/containers/0/env/-
      value:
        name: TEST_VAR
        value: TEST_VALUE
  image: openanalytics/shinyproxy-snapshot:2.3.2-SNAPSHOT-20201002.120450
  fqdn: realm2.shinyproxy-demo.local

